spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuddamu
    username: root
    password: "t3stCr3nd3ntial@2028"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 56f2b58be51b22
    password: 78968897cfcfbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: d125f72e4985aacf783489a955ad93b6aa00a80c111745f69a44b23e578a3954
  expirationMs: 3600000

api:
  username: drh_app
#  username: sandbox
#  key: atsk_7ede1ea879d59af319a4c2636b5d010f5d838f9e9ae4651ff90d4aab35ebab9a5885e081
  key: atsk_2127050ab5ed4a310f09c6ecccb12200da179520d9a9a4c389c053d0ed7806f01a5077eb
